import type { ThemePreset } from "../registry.ts";

export const atelierThemePreset: ThemePreset = {
  key: "atelier",
  label: "Atelier",
  description: "Digital Atelier: monochrome editorial base with signature magenta hierarchy.",
  tokens: {
    canvas: "#F9F9F9",
    surface: "#F9F9F9",
    surfaceAlt: "#F3F3F4",
    surfaceStrong: "#FFFFFF",
    textPrimary: "#1A1C1C",
    textMuted: "#5E5E5E",
    textInverse: "#FFFFFF",
    border: "#E3BDC7",
    borderStrong: "#E3BDC7",
    primary: "#B0004A",
    primaryForeground: "#FFFFFF",
    accent: "#D81B60",
    accentForeground: "#FFFFFF",
    success: "#006630",
    successForeground: "#FFFFFF",
    danger: "#BA1A1A",
    dangerForeground: "#FFFFFF",
    navSolidBg: "#F9F9F9",
    navSolidFg: "#1A1C1C",
    navSolidInteractive: "#B0004A",
    focusRing: "#D81B60",
    shadowSoft: "0 32px 32px rgba(26, 28, 28, 0.04)",
  },
  components: {
    button: {
      primaryBg: "#D81B60",
      primaryFg: "#FFFFFF",
      primaryHoverBg: "#B0004A",
      secondaryBg: "transparent",
      secondaryFg: "#B0004A",
      secondaryHoverBg: "transparent",
      outlineBg: "transparent",
      outlineFg: "#1A1C1C",
      outlineBorder: "rgba(227, 189, 199, 0.15)",
      outlineHoverBg: "transparent",
      outlineHoverFg: "#B0004A",
      ghostFg: "#B0004A",
      ghostHoverBg: "transparent",
      ghostHoverFg: "#B0004A",
      destructiveBg: "#BA1A1A",
      destructiveFg: "#FFFFFF",
      destructiveHoverBg: "#93000A",
      linkFg: "#B0004A",
      linkHoverFg: "#D81B60",
    },
  },
  typography: {
    headingFamily: "Noto Serif",
    bodyFamily: "Noto Serif",
    headingFallback: "serif",
    bodyFallback: "serif",
  },
  radius: {
    sm: "0px",
    md: "0px",
    lg: "0px",
    pill: "0px",
  },
};
